// SPDX-License-Identifier: LGPL-3.0-only
// Adapted from KlN klno.13 (7f3855150586), with CallAI global policy/CAS boundaries.
package service

import("context";"errors";"fmt";"net/http";"reflect";"testing";"time";"github.com/stretchr/testify/require")
func(r *hunterAccounts) CompareAndSwapTurnStateHold(_ context.Context,e *Account,u *time.Time,reason string)(bool,error){r.mu.Lock();defer r.mu.Unlock();if r.fail{return false,errors.New("offline")};a:=r.account;if !reflect.DeepEqual(a.Credentials,e.Credentials)||a.TempUnschedulableReason!=e.TempUnschedulableReason||!reflect.DeepEqual(a.TempUnschedulableUntil,e.TempUnschedulableUntil){return false,nil};a.TempUnschedulableUntil=u;a.TempUnschedulableReason=reason;return true,nil}
func TestHunterHoldLifecycle(t *testing.T){s,a,cfg:=newHunterTest(t);ctx:=context.Background();cfg.HoldWhenDegraded=true;_,err:=s.gateway.settingService.UpdateOpenAIOAuthRuntimePolicy(ctx,&cfg,nil,nil);require.NoError(t,err);req:=stateBoundRequest(s.gateway,a,1,"hold","gpt-test");s.gateway.prepareTurnStateHTTP(req);var fe *UpstreamFailoverError;require.ErrorAs(t,turnStateHoldError(req),&fe);require.Equal(t,503,fe.StatusCode);require.False(t,fe.ShouldReportAccountScheduleFailure());require.Same(t,fe,s.gateway.handleOpenAIUpstreamTransportError(ctx,nil,a,fe,false));latest,err:=s.fresh(ctx,a.ID);require.NoError(t,err);require.Equal(t,"gpt-test",openAITurnStateHeldModel(latest,time.Now()));cfg.HoldWhenDegraded=false;_,err=s.gateway.settingService.UpdateOpenAIOAuthRuntimePolicy(ctx,&cfg,nil,nil);require.NoError(t,err);s.syncHold(ctx,latest);latest,err=s.fresh(ctx,a.ID);require.NoError(t,err);require.Empty(t,latest.TempUnschedulableReason)}
func TestHunterAutoModelsNaturalOnlyAndDisabled(t *testing.T){s,a,cfg:=newHunterTest(t);ctx:=context.Background();cfg.AutoModels=true;cfg.Models=nil;_,err:=s.gateway.settingService.UpdateOpenAIOAuthRuntimePolicy(ctx,&cfg,nil,nil);require.NoError(t,err);req:=stateBoundRequest(s.gateway,a,1,"natural","gpt-other");s.gateway.prepareTurnStateHTTP(req);s.gateway.recordTurnStateObservation(ctx,turnStateAttemptFrom(req.Context()),turnStateFernetBlob(time.Now(),13));require.Equal(t,[]string{"gpt-other"},s.gateway.hunterModelsForAccount(cfg,a.ID,time.Now()));s.gateway.turnStateTraffic.note(a.ID,"gpt-image-2",time.Now());s.gateway.turnStateTraffic.noteMinted(a.ID,"gpt-image-2",time.Now());require.Equal(t,[]string{"gpt-other"},s.gateway.hunterModelsForAccount(cfg,a.ID,time.Now()));cfg.Enabled=false;require.False(t,s.gateway.hunterManagesModel(cfg,a.ID,"gpt-other",time.Now()))}
type hunterKeys struct{APIKeyQuotaUpdater;key *APIKey};func(k hunterKeys)GetByID(context.Context,int64)(*APIKey,error){return k.key,nil}
func TestHunterUsageBillingAndDisabled(t *testing.T){s,a,cfg:=newHunterTest(t);cfg.UsageAPIKeyID=7;cfg.UsageAccountingEnabled=true;s.apiKeys=hunterKeys{key:&APIKey{ID:7,Status:StatusAPIKeyActive,User:&User{ID:1,Status:StatusActive}}};calls:=0;s.recordUsage=func(_ context.Context,in *OpenAIRecordUsageInput)error{calls++;require.Equal(t,RequestTypeTurnStateProbe,in.RequestType);require.Greater(t,in.Result.Usage.InputTokens,0);require.Zero(t,in.Result.Usage.OutputTokens);return nil};req,_:=http.NewRequest(http.MethodPost,"https://example.invalid/responses",nil);s.recordProbeUsage(context.Background(),a,"gpt-5.5",cfg,req,http.Header{},openAITurnStateHuntAttempt{Status:200});require.Equal(t,1,calls);cfg.UsageAccountingEnabled=false;s.recordProbeUsage(context.Background(),a,"gpt-5.5",cfg,req,http.Header{},openAITurnStateHuntAttempt{Status:200});require.Equal(t,1,calls);require.Equal(t,"probe",RequestTypeTurnStateProbe.String())}
func TestHunterConfigCompatibilityAndValidation(t *testing.T){cfg:=DefaultTurnStateHunterSettings();require.True(t,cfg.UsageAccountingEnabled);require.False(t,cfg.HoldWhenDegraded);old,err:=parseOpenAIOAuthRuntimeSettings(`{"openai_oauth_turn_state_hunter":{"enabled":true,"models":["gpt-test"],"proxy_ids":[197],"max_per_hour":6000,"per_account_max_per_hour":500,"gap_seconds":5,"lead_minutes":10,"retry_minutes":10,"idle_minutes":-1,"reasoning_effort":"high"},"openai_oauth_turn_state_auto_enabled":true}`);require.NoError(t,err);require.True(t,old.TurnStateHunter.UsageAccountingEnabled);cfg.Enabled=true;cfg.AutoModels=true;cfg.ProxyIDs=[]int64{197};cfg.RotatingProxyIDs=[]int64{197};require.NoError(t,cfg.validate());for _,ids:=range[][]int64{{1},{197,197},{-1}}{cfg.RotatingProxyIDs=ids;require.Error(t,cfg.validate(),fmt.Sprint(ids))}}
